# app_home:
#   path: /
#   controller: App\Controller\HomeController::index

# app_voiture:
#   path: /voitures
#   controller: App\Controller\VehiculeController::allVoitures

app_cgv:
  path: /cgv
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: "static/cgv.html.twig"
