#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# app_home:
#   path: /
#   controller: App\Controller\VehiculeController::index
# app_voiture:
#   path: /voitures
#   controller: App\Controller\VehiculeController::allVoitures
